import oracledb

# Configuración de conexión (ajústalo a tu entorno)
DB_CONFIG = {
    "user": "system",
    "password": "oracle",
    "dsn": "localhost:1521/XEPDB1",  # Ejemplo con Oracle XE
    "encoding": "UTF-8"
}

def get_connection():
    try:
        conn = oracledb.connect(**DB_CONFIG)
        return conn
    except Exception as e:
        raise Exception(f"Error conectando a Oracle: {e}")

# 1. Verificar conexión
def check_connection():
    conn = get_connection()
    conn.close()
    return True

# 2. Crear / Eliminar Base de Datos (en Oracle se suele manejar "Schemas")
def create_user(user: str, password: str):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute(f"CREATE USER {user} IDENTIFIED BY {password}")
    cur.execute(f"GRANT CONNECT, RESOURCE TO {user}")
    conn.commit()
    conn.close()
    return True

def drop_user(user: str):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute(f"DROP USER {user} CASCADE")
    conn.commit()
    conn.close()
    return True

# 3. Crear / Eliminar Tabla
def create_table():
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE usuarios (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR2(100),
            email VARCHAR2(100)
        )
    """)
    conn.commit()
    conn.close()
    return True

def drop_table():
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("DROP TABLE usuarios PURGE")
    conn.commit()
    conn.close()
    return True

# 4. CRUD
def insert_usuario(nombre: str, email: str):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("INSERT INTO usuarios (nombre, email) VALUES (:1, :2)", (nombre, email))
    conn.commit()
    conn.close()
    return True

def get_usuarios():
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("SELECT id, nombre, email FROM usuarios")
    rows = cur.fetchall()
    conn.close()
    return [{"id": r[0], "nombre": r[1], "email": r[2]} for r in rows]

def update_usuario(user_id: int, nombre: str, email: str):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("UPDATE usuarios SET nombre=:1, email=:2 WHERE id=:3", (nombre, email, user_id))
    conn.commit()
    conn.close()
    return True

def delete_usuario(user_id: int):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("DELETE FROM usuarios WHERE id=:1", (user_id,))
    conn.commit()
    conn.close()
    return True
